export const ClassStat = {
  0: {
    Name: "Normal Soldier",
    HP: 15,
    HpGrowth: 0.5,
    Strength: 5,
    StrGrowth: 0.45,
    Skill: 6,
    SklGrowth: 0.4,
    Speed: 5,
    SpdGrowth: 0.4,
    Luck: 5,
    LckGrowth: 0.4,
    Defence: 6,
    DefGrowth: 0.5,
    Resistance: 4,
    ResGrowth: 0.3,
    Movement: 5,
  },
  1: {
    Name: "Water Pirate",
    HP: 17,
    HpGrowth: 0.6,
    Strength: 7,
    StrGrowth: 0.5,
    Skill: 5,
    SklGrowth: 0.4,
    Speed: 5,
    SpdGrowth: 0.5,
    Luck: 5,
    LckGrowth: 0.3,
    Defence: 6,
    DefGrowth: 0.5,
    Resistance: 5,
    ResGrowth: 0.4,
    Movement: 5,
  },
  2: {
    Name: "Steel Armor",
    HP: 15,
    HpGrowth: 0.6,
    Strength: 7,
    StrGrowth: 0.5,
    Skill: 6,
    SklGrowth: 0.5,
    Speed: 4,
    SpdGrowth: 0.3,
    Luck: 5,
    LckGrowth: 0.4,
    Defence: 7,
    DefGrowth: 0.7,
    Resistance: 6,
    ResGrowth: 0.2,
    Movement: 4,
  },
  3: {
    Name: "Flying Rider",
    HP: 13,
    HpGrowth: 0.4,
    Strength: 7,
    StrGrowth: 0.4,
    Skill: 7,
    SklGrowth: 0.6,
    Speed: 7,
    SpdGrowth: 0.7,
    Luck: 6,
    LckGrowth: 0.5,
    Defence: 6,
    DefGrowth: 0.35,
    Resistance: 4,
    ResGrowth: 0.55,
    Movement: 7,
  },
  4: {
    Name: "Ground Rider",
    HP: 15,
    HpGrowth: 0.5,
    Strength: 8,
    StrGrowth: 0.45,
    Skill: 6,
    SklGrowth: 0.5,
    Speed: 6,
    SpdGrowth: 0.6,
    Luck: 4,
    LckGrowth: 0.4,
    Defence: 6,
    DefGrowth: 0.5,
    Resistance: 4,
    ResGrowth: 0.3,
    Movement: 7,
  },
  5: {
    Name: "Dragonkind",
    HP: 18,
    HpGrowth: 0.6,
    Strength: 6,
    StrGrowth: 0.7,
    Skill: 6,
    SklGrowth: 0.5,
    Speed: 6,
    SpdGrowth: 0.45,
    Luck: 5,
    LckGrowth: 0.4,
    Defence: 5,
    DefGrowth: 0.55,
    Resistance: 5,
    ResGrowth: 0.5,
    Movement: 6,
  },
  6: {
    Name: "Fire Mage",
    HP: 14,
    HpGrowth: 0.45,
    Magic: 7,
    MagGrowth: 0.6,
    Skill: 6,
    SklGrowth: 0.5,
    Speed: 6,
    SpdGrowth: 0.5,
    Luck: 4,
    LckGrowth: 0.4,
    Defence: 5,
    DefGrowth: 0.5,
    Resistance: 7,
    ResGrowth: 0.4,
    Movement: 5,
  },
  7: {
    Name: "Electric Mage",
    HP: 13,
    HpGrowth: 0.4,
    Magic: 6,
    MagGrowth: 0.55,
    Skill: 7,
    SklGrowth: 0.6,
    Speed: 7,
    SpdGrowth: 0.6,
    Luck: 5,
    LckGrowth: 0.5,
    Defence: 6,
    DefGrowth: 0.35,
    Resistance: 6,
    ResGrowth: 0.55,
    Movement: 5,
  },
  8: {
    Name: "Ice Mage",
    HP: 13,
    HpGrowth: 0.45,
    Magic: 7,
    MagGrowth: 0.75,
    Skill: 5,
    SklGrowth: 0.4,
    Speed: 5,
    SpdGrowth: 0.4,
    Luck: 6,
    LckGrowth: 0.5,
    Defence: 4,
    DefGrowth: 0.35,
    Resistance: 5,
    ResGrowth: 0.4,
    Movement: 5,
  },
};

export const EquipStat = {
  0: {
    Name: "Brick Break",
    Classes: ["Normal Soldier", "Steel Armor", "Ground Rider"],
    Durability: 20,
    Range_min: 1,
    Range_max: 1,
    Might: 6,
    Weight: 5,
    Hit_rate: 90,
    Critical_rate: 5,
    Double_might: ["Steel Armor"],
  },
  1: {
    Name: "Knock Down",
    Classes: ["Normal Soldier", "Steel Armor", "Ground Rider", "Flying Rider"],
    Durability: 20,
    Range_min: 1,
    Range_max: 1,
    Might: 6,
    Weight: 5,
    Hit_rate: 90,
    Critical_rate: 5,
    Double_might: ["Flying Rider"],
  },
  2: {
    Name: "Dragon Claw",
    Classes: ["Normal Soldier", "Steel Armor", "Water Pirate", "Dragonkind"],
    Durability: 20,
    Range_min: 1,
    Range_max: 1,
    Might: 7,
    Weight: 5,
    Hit_rate: 90,
    Critical_rate: 0,
    Double_might: ["Dragonkind"],
  },
  3: {
    Name: "Discharge",
    Classes: ["Electric Mage"],
    Durability: 20,
    Range_min: 1,
    Range_max: 2,
    Might: 5,
    Weight: 5,
    Hit_rate: 95,
    Critical_rate: 0,
    Double_might: ["Water Pirate"],
  },
  4: {
    Name: "Burnout",
    Classes: ["Fire Mage"],
    Durability: 20,
    Range_min: 1,
    Range_max: 2,
    Might: 5,
    Weight: 5,
    Hit_rate: 95,
    Critical_rate: 0,
    Double_might: ["Fire Mage", "Electirc Mage", "Ice Mage"],
  },
  5: {
    Name: "Grass Knot",
    Classes: ["Ice Mage"],
    Durability: 20,
    Range_min: 1,
    Range_max: 2,
    Might: 5,
    Weight: 5,
    Hit_rate: 95,
    Critical_rate: 0,
    Double_might: ["Ground Rider"],
  },
  6: {
    Name: "Tackle",
    Classes: ["Normal Soldier", "Steel Armor", "Ground Rider", "Flying Rider"],
    Durability: 45,
    Range_min: 1,
    Range_max: 1,
    Might: 3,
    Weight: 2,
    Hit_rate: 90,
    Critical_rate: 0,
    Double_might: [],
  },
  7: {
    Name: "Wing Attack",
    Classes: ["Normal Soldier", "Steel Armor", "Ground Rider", "Flying Rider"],
    Durability: 30,
    Range_min: 1,
    Range_max: 1,
    Might: 6,
    Weight: 4,
    Hit_rate: 85,
    Critical_rate: 5,
    Double_might: [],
  },
  8: {
    Name: "Slash",
    Classes: ["Normal Soldier", "Steel Armor", "Ground Rider", "Flying Rider"],
    Durability: 20,
    Range_min: 1,
    Range_max: 1,
    Might: 5,
    Weight: 5,
    Hit_rate: 90,
    Critical_rate: 30,
    Double_might: [],
  },
  9: {
    Name: "Iron Tail",
    Classes: ["Normal Soldier", "Steel Armor", "Ground Rider", "Flying Rider"],
    Durability: 20,
    Range_min: 1,
    Range_max: 2,
    Might: 4,
    Weight: 3,
    Hit_rate: 75,
    Critical_rate: 0,
    Double_might: [],
  },
  10: {
    Name: "Double Hit",
    Classes: ["Normal Soldier", "Steel Armor", "Ground Rider", "Flying Rider"],
    Durability: 30,
    Range_min: 1,
    Range_max: 1,
    Might: 5,
    Weight: 5,
    Hit_rate: 85,
    Critical_rate: 0,
    Double_might: [],
  },
  11: {
    Name: "High Horsepower",
    Classes: ["Normal Soldier", "Steel Armor", "Ground Rider", "Flying Rider"],
    Durability: 15,
    Range_min: 1,
    Range_max: 1,
    Might: 8,
    Weight: 7,
    Hit_rate: 80,
    Critical_rate: 10,
    Double_might: [],
  },
  12: {
    Name: "Water Gun",
    Classes: ["Water Pirate", "Dragonkind"],
    Durability: 45,
    Range_min: 1,
    Range_max: 1,
    Might: 4,
    Weight: 3,
    Hit_rate: 85,
    Critical_rate: 0,
    Double_might: [],
  },
  13: {
    Name: "Dragon Rage",
    Classes: ["Water Pirate", "Dragonkind"],
    Durability: 30,
    Range_min: 1,
    Range_max: 1,
    Might: 6,
    Weight: 5,
    Hit_rate: 85,
    Critical_rate: 5,
    Double_might: [],
  },
  14: {
    Name: "Crabhammer",
    Classes: ["Water Pirate", "Dragonkind"],
    Durability: 20,
    Range_min: 1,
    Range_max: 1,
    Might: 6,
    Weight: 5,
    Hit_rate: 90,
    Critical_rate: 30,
    Double_might: [],
  },
  15: {
    Name: "Water Shuriken",
    Classes: ["Water Pirate", "Dragonkind"],
    Durability: 20,
    Range_min: 1,
    Range_max: 2,
    Might: 5,
    Weight: 4,
    Hit_rate: 70,
    Critical_rate: 0,
    Double_might: [],
  },
  16: {
    Name: "Dual Chop",
    Classes: ["Dragonkind"],
    Durability: 30,
    Range_min: 1,
    Range_max: 1,
    Might: 6,
    Weight: 6,
    Hit_rate: 85,
    Critical_rate: 5,
    Double_might: [],
  },
  17: {
    Name: "Dragon Rush",
    Classes: ["Dragonkind"],
    Durability: 15,
    Range_min: 1,
    Range_max: 1,
    Might: 10,
    Weight: 8,
    Hit_rate: 70,
    Critical_rate: 10,
    Double_might: [],
  },
  18: {
    Name: "Waterfall",
    Classes: ["Water Pirate"],
    Durability: 15,
    Range_min: 1,
    Range_max: 1,
    Might: 9,
    Weight: 7,
    Hit_rate: 75,
    Critical_rate: 5,
    Double_might: [],
  },
  19: {
    Name: "Ember",
    Classes: ["Fire Mage"],
    Durability: 40,
    Range_min: 1,
    Range_max: 2,
    Might: 3,
    Weight: 4,
    Hit_rate: 95,
    Critical_rate: 5,
    Double_might: [],
  },
  20: {
    Name: "Flamethrower",
    Classes: ["Fire Mage"],
    Durability: 30,
    Range_min: 1,
    Range_max: 2,
    Might: 6,
    Weight: 5,
    Hit_rate: 85,
    Critical_rate: 5,
    Double_might: [],
  },
  21: {
    Name: "Fire Blast",
    Classes: ["Fire Mage"],
    Durability: 20,
    Range_min: 1,
    Range_max: 2,
    Might: 9,
    Weight: 8,
    Hit_rate: 75,
    Critical_rate: 5,
    Double_might: [],
  },
  22: {
    Name: "Thunder Shock",
    Classes: ["Electric Mage"],
    Durability: 40,
    Range_min: 1,
    Range_max: 2,
    Might: 3,
    Weight: 3,
    Hit_rate: 90,
    Critical_rate: 5,
    Double_might: [],
  },
  23: {
    Name: "Thunderbolt",
    Classes: ["Electric Mage"],
    Durability: 30,
    Range_min: 1,
    Range_max: 2,
    Might: 6,
    Weight: 5,
    Hit_rate: 80,
    Critical_rate: 0,
    Double_might: [],
  },
  24: {
    Name: "Thunder",
    Classes: ["Electric Mage"],
    Durability: 20,
    Range_min: 1,
    Range_max: 2,
    Might: 9,
    Weight: 7,
    Hit_rate: 70,
    Critical_rate: 0,
    Double_might: [],
  },
  25: {
    Name: "Powder Snow",
    Classes: ["Ice Mage"],
    Durability: 40,
    Range_min: 1,
    Range_max: 2,
    Might: 4,
    Weight: 5,
    Hit_rate: 85,
    Critical_rate: 0,
    Double_might: [],
  },
  26: {
    Name: "Ice Beam",
    Classes: ["Fire Mage"],
    Durability: 30,
    Range_min: 1,
    Range_max: 2,
    Might: 7,
    Weight: 6,
    Hit_rate: 80,
    Critical_rate: 0,
    Double_might: [],
  },
  27: {
    Name: "Blizzard",
    Classes: ["Ice Mage"],
    Durability: 20,
    Range_min: 1,
    Range_max: 2,
    Might: 10,
    Weight: 8,
    Hit_rate: 70,
    Critical_rate: 5,
    Double_might: [],
  },
};
