export const ClassStat = {
  0: {
    Name: "Normal Soldier",
    HP: 15,
    HpGrowth: 0.5,
    Strength: 5,
    StrGrowth: 0.45,
    Skill: 6,
    SklGrowth: 0.4,
    Speed: 5,
    SpdGrowth: 0.4,
    Luck: 5,
    LckGrowth: 0.4,
    Defence: 6,
    DefGrowth: 0.5,
    Resistance: 4,
    ResGrowth: 0.3,
    Movement: 5,
  },
  1: {
    Name: "Water Pirate",
    HP: 17,
    HpGrowth: 0.6,
    Strength: 7,
    StrGrowth: 0.5,
    Skill: 5,
    SklGrowth: 0.4,
    Speed: 5,
    SpdGrowth: 0.5,
    Luck: 5,
    LckGrowth: 0.3,
    Defence: 6,
    DefGrowth: 0.5,
    Resistance: 5,
    ResGrowth: 0.4,
    Movement: 5,
  },
  2: {
    Name: "Steel Armor",
    HP: 15,
    HpGrowth: 0.6,
    Strength: 7,
    StrGrowth: 0.5,
    Skill: 6,
    SklGrowth: 0.5,
    Speed: 4,
    SpdGrowth: 0.3,
    Luck: 5,
    LckGrowth: 0.4,
    Defence: 7,
    DefGrowth: 0.7,
    Resistance: 6,
    ResGrowth: 0.2,
    Movement: 4,
  },
  3: {
    Name: "Flying Rider",
    HP: 13,
    HpGrowth: 0.4,
    Strength: 7,
    StrGrowth: 0.4,
    Skill: 7,
    SklGrowth: 0.6,
    Speed: 7,
    SpdGrowth: 0.7,
    Luck: 6,
    LckGrowth: 0.5,
    Defence: 6,
    DefGrowth: 0.35,
    Resistance: 4,
    ResGrowth: 0.55,
    Movement: 7,
  },
  4: {
    Name: "Ground Rider",
    HP: 15,
    HpGrowth: 0.5,
    Strength: 8,
    StrGrowth: 0.45,
    Skill: 6,
    SklGrowth: 0.5,
    Speed: 6,
    SpdGrowth: 0.6,
    Luck: 4,
    LckGrowth: 0.4,
    Defence: 6,
    DefGrowth: 0.5,
    Resistance: 4,
    ResGrowth: 0.3,
    Movement: 7,
  },
  5: {
    Name: "Dragonkind",
    HP: 18,
    HpGrowth: 0.6,
    Strength: 6,
    StrGrowth: 0.7,
    Skill: 6,
    SklGrowth: 0.5,
    Speed: 6,
    SpdGrowth: 0.45,
    Luck: 5,
    LckGrowth: 0.4,
    Defence: 5,
    DefGrowth: 0.55,
    Resistance: 5,
    ResGrowth: 0.5,
    Movement: 6,
  },
  6: {
    Name: "Fire Mage",
    HP: 14,
    HpGrowth: 0.45,
    Magic: 7,
    MagGrowth: 0.6,
    Skill: 6,
    SklGrowth: 0.5,
    Speed: 6,
    SpdGrowth: 0.5,
    Luck: 4,
    LckGrowth: 0.4,
    Defence: 5,
    DefGrowth: 0.5,
    Resistance: 7,
    ResGrowth: 0.4,
    Movement: 5,
  },
  7: {
    Name: "Electric Mage",
    HP: 13,
    HpGrowth: 0.4,
    Magic: 6,
    MagGrowth: 0.55,
    Skill: 7,
    SklGrowth: 0.6,
    Speed: 7,
    SpdGrowth: 0.6,
    Luck: 5,
    LckGrowth: 0.5,
    Defence: 6,
    DefGrowth: 0.35,
    Resistance: 6,
    ResGrowth: 0.55,
    Movement: 5,
  },
  8: {
    Name: "Ice Mage",
    HP: 13,
    HpGrowth: 0.45,
    Magic: 7,
    MagGrowth: 0.75,
    Skill: 5,
    SklGrowth: 0.4,
    Speed: 5,
    SpdGrowth: 0.4,
    Luck: 6,
    LckGrowth: 0.5,
    Defence: 4,
    DefGrowth: 0.35,
    Resistance: 5,
    ResGrowth: 0.4,
    Movement: 5,
  },
};

export const EquipStat = {
  "Brick Break": { Mt: 5 },
};
